version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: recipes
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  recipe-service:
    build: ./services/recipe-service
    environment:
      DATABASE_URL: postgres://postgres:secret@db:5432/recipes
      PORT: 3000
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SPOONACULAR_KEY: ${SPOONACULAR_KEY}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  db-data:
